In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('./players_20.csv')
df.set_index('short_name',inplace=True)
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [9]:
df.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

selecting with single value

In [10]:
df.loc['L. Messi']

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [11]:
df.loc['L. Messi','height_cm']

np.int64(170)

In [15]:
df.loc['Cristiano Ronaldo','weight_kg']

np.int64(83)

In [16]:
df.loc[:,'height_cm']

short_name
L. Messi             170
Cristiano Ronaldo    187
Neymar Jr            175
J. Oblak             188
E. Hazard            175
                    ...
Shao Shuai           186
Xiao Mingjie         177
Zhang Wei            186
Wang Haijian         185
Pan Ximing           182
Name: height_cm, Length: 18278, dtype: int64

In [20]:
df.loc['L. Messi', :]

long_name      Lionel Andrés Messi Cuccittini
age                                        32
dob                                1987-06-24
height_cm                                 170
weight_kg                                  72
nationality                         Argentina
club                             FC Barcelona
Name: L. Messi, dtype: object

In [27]:
import pandas as pd

# Create the DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 28, 22],
    'City': ['New York', 'London', 'Paris', 'Berlin', 'Tokyo'],
    'Score': [88, 92, 85, 90, 95]
}

df = pd.DataFrame(data, index=['a', 'b', 'c', 'd', 'e'])

# Show the DataFrame
print("=== DataFrame ===")
print(df)

# 🧩 5 Best Practice Questions Using .loc[] (Write your answers below each)

# 1️⃣ Get the full row for the person named 'Charlie' (hint: use label)
df.loc['c',:]
# 2️⃣ Show the 'Name' and 'City' for all people with Score greater than 90
df.loc[df['Score']>90,['Name','City']]
# 3️⃣ Select all rows from 'b' to 'd' (inclusive) and show only 'Age' and 'Score'
df.loc['b':'d',['Age','Score']]
# 4️⃣ Find all people younger than 30 and display their 'Name' and 'Score'
df.loc[df['Age']<30,['Name','Score']]
# 5️⃣ Update the 'City' of the person with index label 'a' to 'San Francisco'
df.loc['a' ,'City'] = 'San Francisco'
df
# ✅ Run and print your answers after each question to check your understanding!

=== DataFrame ===
      Name  Age      City  Score
a    Alice   25  New York     88
b      Bob   30    London     92
c  Charlie   35     Paris     85
d    David   28    Berlin     90
e      Eva   22     Tokyo     95

      Name  Age           City  Score
a    Alice   25  San Francisco     88
b      Bob   30         London     92
c  Charlie   35          Paris     85
d    David   28         Berlin     90
e      Eva   22          Tokyo     95