In [1]:
import pandas as pd

inventory = pd.DataFrame({
    'Item': ['Apples', 'Milk', 'Eggs', 'Bread', 'Cheese', 'Chicken'],
    'Category': ['Produce', 'Dairy', 'Dairy', 'Bakery', 'Dairy', 'Meat'],
    'Price': [2.99, 3.49, 4.19, 2.49, 5.99, 8.99],
    'Quantity': [150, 80, 120, 95, 60, 45],
    'Perishable': [True, True, True, False, True, True]
})

In [7]:
def make_price_label(price):
    if price <3:
        return "Budget"
    elif price<6:
        return "Standard"
    else:
        return "Premium"
    
inventory['Price_Label'] = inventory['Price'].apply(make_price_label)
inventory

      Item Category  Price  Quantity  Perishable Price_Label
0   Apples  Produce   2.99       150        True      Budget
1     Milk    Dairy   3.49        80        True    Standard
2     Eggs    Dairy   4.19       120        True    Standard
3    Bread   Bakery   2.49        95       False      Budget
4   Cheese    Dairy   5.99        60        True    Standard
5  Chicken     Meat   8.99        45        True     Premium

In [9]:
def  restock_check(quantity):
    if quantity < 50:
        return "Urgent"
    elif quantity < 100:
        return "Monitor"
    else :
        return "Adequate"
    
inventory['Stock_Status'] = inventory['Quantity'].apply(restock_check)
inventory

      Item Category  Price  Quantity  Perishable Price_Label Stock_Status
0   Apples  Produce   2.99       150        True      Budget     Adequate
1     Milk    Dairy   3.49        80        True    Standard      Monitor
2     Eggs    Dairy   4.19       120        True    Standard     Adequate
3    Bread   Bakery   2.49        95       False      Budget      Monitor
4   Cheese    Dairy   5.99        60        True    Standard      Monitor
5  Chicken     Meat   8.99        45        True     Premium       Urgent

In [10]:
def describe_item(row):
    return f"{row['Item']} {row['Category']} - {row['Price']}"

inventory['Description'] = inventory.apply(describe_item,axis= 1)
inventory

,Item,Category,Price,Quantity,Perishable,Price_Label,Stock_Status,Description
0,Apples,Produce,2.99,150,True,Budget,Adequate,Apples Produce - 2.99
1,Milk,Dairy,3.49,80,True,Standard,Monitor,Milk Dairy - 3.49
2,Eggs,Dairy,4.19,120,True,Standard,Adequate,Eggs Dairy - 4.19
3,Bread,Bakery,2.49,95,False,Budget,Monitor,Bread Bakery - 2.49
4,Cheese,Dairy,5.99,60,True,Standard,Monitor,Cheese Dairy - 5.99
5,Chicken,Meat,8.99,45,True,Premium,Urgent,Chicken Meat - 8.99

In [12]:
def storage_needs(row):
    if row['Perishable']:
        return 'Refrigerate'
    elif (row['Perishable'] == False) and (row['Category'] == 'Bakery'):
        return 'Shelf'
    else:
        return "Dry Storage"
    
inventory['Storage'] = inventory.apply(storage_needs,axis=1)
inventory

,Item,Category,Price,Quantity,Perishable,Price_Label,Stock_Status,Description,Storage
0,Apples,Produce,2.99,150,True,Budget,Adequate,Apples Produce - 2.99,Refrigerate
1,Milk,Dairy,3.49,80,True,Standard,Monitor,Milk Dairy - 3.49,Refrigerate
2,Eggs,Dairy,4.19,120,True,Standard,Adequate,Eggs Dairy - 4.19,Refrigerate
3,Bread,Bakery,2.49,95,False,Budget,Monitor,Bread Bakery - 2.49,Shelf
4,Cheese,Dairy,5.99,60,True,Standard,Monitor,Cheese Dairy - 5.99,Refrigerate
5,Chicken,Meat,8.99,45,True,Premium,Urgent,Chicken Meat - 8.99,Refrigerate

In [14]:
def order_priority(row):
    if (row['Price'] > 5) and (row['Quantity'] < 75):
        return 'High'
    elif  (row['Price'] > 3) or (row['Quantity'] < 100):
        return "Medium"
    else:
        return 'Low'
    
inventory['Priority'] = inventory.apply(order_priority,axis = 1)
inventory

,Item,Category,Price,Quantity,Perishable,Price_Label,Stock_Status,Description,Storage,Priority
0,Apples,Produce,2.99,150,True,Budget,Adequate,Apples Produce - 2.99,Refrigerate,Low
1,Milk,Dairy,3.49,80,True,Standard,Monitor,Milk Dairy - 3.49,Refrigerate,Medium
2,Eggs,Dairy,4.19,120,True,Standard,Adequate,Eggs Dairy - 4.19,Refrigerate,Medium
3,Bread,Bakery,2.49,95,False,Budget,Monitor,Bread Bakery - 2.49,Shelf,Medium
4,Cheese,Dairy,5.99,60,True,Standard,Monitor,Cheese Dairy - 5.99,Refrigerate,High
5,Chicken,Meat,8.99,45,True,Premium,Urgent,Chicken Meat - 8.99,Refrigerate,High