In [1]:
import pandas as pd

In [7]:
df_movies = pd.read_csv('IMDb movies.csv',low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv')

In [9]:
df_ratings.columns

Index(['imdb_title_id', 'weighted_average_vote', 'total_votes', 'mean_vote',
       'median_vote', 'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6',
       'votes_5', 'votes_4', 'votes_3', 'votes_2', 'votes_1',
       'allgenders_0age_avg_vote', 'allgenders_0age_votes',
       'allgenders_18age_avg_vote', 'allgenders_18age_votes',
       'allgenders_30age_avg_vote', 'allgenders_30age_votes',
       'allgenders_45age_avg_vote', 'allgenders_45age_votes',
       'males_allages_avg_vote', 'males_allages_votes', 'males_0age_avg_vote',
       'males_0age_votes', 'males_18age_avg_vote', 'males_18age_votes',
       'males_30age_avg_vote', 'males_30age_votes', 'males_45age_avg_vote',
       'males_45age_votes', 'females_allages_avg_vote',
       'females_allages_votes', 'females_0age_avg_vote', 'females_0age_votes',
       'females_18age_avg_vote', 'females_18age_votes',
       'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

In [10]:
df_movies = df_movies[['imdb_title_id', 'title', 'year','genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes','mean_vote']]

In [11]:
df_sample = df_movies.sample(frac = 0.5)

In [12]:
df_sample_conct = pd.concat([df_movies,df_ratings],axis=0)

In [13]:
df_sample.shape

(42928, 5)

In [14]:

df_concat_horizontally = pd.concat([df_movies,df_ratings],axis=1)

In [15]:
df_concat_horizontally

,imdb_title_id,title,year,genre,country,imdb_title_id,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,tt0000009,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,tt0000574,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",tt0001892,188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,tt0002101,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,tt0002130,2237,6.9
...,...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",tt9908390,398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,tt9911196,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,tt9911774,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,tt9914286,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,tt9914942,102,6.8

In [21]:
import pandas as pd

employees = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'Tech', 'Marketing', 'Finance']
})

salaries = pd.DataFrame({
    'ID': [1, 2, 3, 5],
    'Salary': [50000, 60000, 55000, 70000]
})

merged_pd = employees.merge(salaries,on = 'ID',how = 'inner')
meged_pd_full = employees.merge(salaries,on='ID',how='outer')

meged_pd_full

   ID     Name Department   Salary
0   1    Alice         HR  50000.0
1   2      Bob       Tech  60000.0
2   3  Charlie  Marketing  55000.0
3   4    David    Finance      NaN
4   5      NaN        NaN  70000.0

In [19]:
df_movies.merge(df_ratings,on = 'imdb_title_id',how = 'inner')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [23]:
import pandas as pd
import numpy as np  # For NaN values

# Employees DataFrame (some departments missing)
employees = pd.DataFrame({
    'Employee_ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'Tech', np.nan, 'Finance']  # Charlie's department missing
})

# Salaries DataFrame (some salaries missing)
salaries = pd.DataFrame({
    'Employee_ID': [101, 102, 104, 105],  # 103 missing, 105 extra
    'Salary': [50000, np.nan, 70000, 80000]  # Bob's salary missing
})

merged_outer = employees.merge(salaries,on='Employee_ID',how='outer')
merged_outer

   Employee_ID     Name Department   Salary
0          101    Alice         HR  50000.0
1          102      Bob       Tech      NaN
2          103  Charlie        NaN      NaN
3          104    David    Finance  70000.0
4          105      NaN        NaN  80000.0