In [1]:
import pandas as pd

In [6]:
df_laptops = pd.read_csv('laptop_price.csv',encoding='latin-1')
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

Create a column based on one condition np.where()

In [5]:
import numpy as np

In [ ]:
#this creates a series of cheap or expensive laptops
np.where(df_laptops['Price_euros'] > 2000,'Expensive','Cheap')

array(['Cheap', 'Cheap', 'Cheap', ..., 'Cheap', 'Cheap', 'Cheap'],
      shape=(1303,), dtype='<U9')

In [8]:
df_laptops['Price_tier'] = np.where(df_laptops['Price_euros'] > 2000,'Expensive','Cheap')

In [9]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Price_tier
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Cheap
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Cheap
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Cheap
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Expensive
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Cheap

In [10]:
df_laptops.value_counts('Price_tier')

Price_tier
Cheap        1166
Expensive     137
Name: count, dtype: int64

Exercises

In [11]:
np.where(df_laptops['Inches']>15,"Big","Small")

array(['Small', 'Small', 'Big', ..., 'Small', 'Big', 'Big'],
      shape=(1303,), dtype='<U5')

In [12]:
df_laptops["Screen Status"] = np.where(df_laptops['Inches']>15,"Big","Small")

In [ ]:
df_laptops.head()

Practice 2

In [ ]:
import pandas as pd
import numpy as np

# 🧪 Sample Data
data = {
    'Laptop': ['Dell XPS', 'HP Pavilion', 'MacBook Air', 'Lenovo IdeaPad', 'Acer Aspire', 'Asus ZenBook'],
    'Inches': [13.3, 15.6, 13.0, 16.1, 14.0, 15.0],
    'RAM': [8, 16, 8, 32, 4, 16],
    'Price': [1200, 850, 999, 1300, 500, 1100]
}

df_laptops = pd.DataFrame(data)
print(df_laptops)
# 1️⃣ Add a new column 'Size Category' with values:
#    - "Big" if Inches > 15
#    - "Small" otherwise
df_laptops['Size Category'] = np.where(df_laptops['Inches']>15,"Big","Small")
# 2️⃣ Create a column 'RAM Status':
#    - "High RAM" if RAM >= 16
#    - "Low RAM" if RAM < 16
df_laptops['RAM Status'] = np.where(df_laptops['RAM']>=16,"High RAM","Low RAM")
# 3️⃣ Add a column 'Budget':
#    - "Expensive" if Price > 1000
#    - "Affordable" otherwise
df_laptops['Budget'] = np.where(df_laptops['Price'] >1000,"Expensive","Affordable")
df_laptops.head()
# 4️⃣ Create a column 'Ultra Portable':
#    - "Yes" if Inches < 14 and Weight < 1.5 (assume you add a Weight column)
#    - "No" otherwise
#    (Hint: Add a column df_laptops['Weight'] = [1.2, 2.1, 1.1, 2.4, 1.8, 1.4])
df_laptops['Weight'] = [1.2, 2.1, 1.1, 2.4, 1.8, 1.4]
df_laptops['Ultra Portable'] = np.where(df_laptops)
# 5️⃣ Create a column 'Performance Tag':
#    - "Pro" if RAM >= 16 and Price > 1000
#    - "Standard" otherwise

           Laptop  Inches  RAM  Price
0        Dell XPS    13.3    8   1200
1     HP Pavilion    15.6   16    850
2     MacBook Air    13.0    8    999
3  Lenovo IdeaPad    16.1   32   1300
4     Acer Aspire    14.0    4    500
5    Asus ZenBook    15.0   16   1100