In [2]:
import pandas as pd 
import numpy as np

In [4]:
df_laptops = pd.read_csv('laptop_price.csv',encoding='latin-1')
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [12]:
conditions = [df_laptops['Inches'] > 16,
              df_laptops['Inches'] > 14,
              df_laptops['Inches'] > 12,
              df_laptops['Inches']<12]

values = ['Too Big','Big','Small','Too small']

In [16]:
df_laptops['Screen Size']=np.select(conditions,values,default='other')

In [17]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Screen Size
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Small
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Small
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Big
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Big
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Small

In [ ]:
df_laptops['Screen Size'].value_counts()

In [34]:

import pandas as pd
import numpy as np

# Sample DataFrame
data = {
    'Student': ['Amy', 'Brian', 'Clara', 'Dan', 'Ella'],
    'Score': [95, 83, 76, 68, 59],
    'Attendance': [98, 89, 75, 70, 65]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# -------------------------------------
# 📌 Question 1:
# Create a column "Grade" based on the following:
# - "A" if Score >= 90
# - "B" if Score is between 80–89
# - "C" if Score is between 70–79
# - "D" if Score is between 60–69
# - "F" otherwise

conditions1 = [
    df['Score'] >= 90,
    df['Score'] >= 80,
    df['Score'] >= 70,
    df['Score'] >= 60,
    df['Score'] < 60
]
values1 = ["A","B","C","D","F"]
df["Grade"] = np.select(conditions1,values1,default='other')

# -------------------------------------
# 📌 Question 2:
# Create a column "Discipline" based on Attendance:
# - "Excellent" if Attendance >= 95
# - "Good" if Attendance is between 85–94
# - "Average" if Attendance is between 70–84
# - "Poor" otherwise

# Your code here using np.select()
conditions2 = [
    df['Attendance']>=95,
    df['Attendance']>=85,
    df['Attendance']>=70,
    df['Attendance']<70
]
values2 = ["Excellent","Good","Average","Poor"]
df["Discipline"] = np.select(conditions2,values2,default='other')
# -------------------------------------
# 📌 Question 3:
# Create a column "Final_Remark" based on Grade and Discipline:
# - "Outstanding" if Grade is "A" and Discipline is "Excellent"
# - "Very Good" if Grade is "B" and Discipline is "Good"
# - "Needs Improvement" otherwise

conditions3 = [
    (df['Grade'] == 'A') & (df["Discipline"] == "Excellent"),
    (df['Grade'] == 'B') & (df["Discipline"] == "Good"),
    ((df['Grade'] == 'C') | (df['Grade'] == 'D') | (df['Grade'] == 'F'))
]
values3 = [ "Outstanding","Very Good","Needs Improvement"]
df["Final_Remark"] = np.select(conditions3,values3,default='other')
df

# -------------------------------------
# 📌 Question 4:
# Create a column "Award" based on Score and Attendance:
# - "Gold" if Score >= 90 and Attendance >= 95
# - "Silver" if Score >= 80 and Attendance >= 90
# - "Bronze" if Score >= 70 and Attendance >= 85
# - "None" otherwise

conditions4 = [
    (df['Score'] >= 90) & (df['Attendance'] >= 95),
    (df['Score'] >= 80) & (df['Attendance'] >= 90),
    (df['Score'] >= 70) & (df['Attendance'] >= 85),
    (df['Score'] < 70)
]
values4 = ["Gold","Silver","Bronze","None"]
df["Award"] = np.select(conditions4,values4,default='other')
df

# -------------------------------------
# 📌 Question 5:
# Create a column "Status" based on Score and Attendance:
# - "Promoted" if Score >= 60 and Attendance >= 70
# - "Not Promoted" otherwise
conditions5 = [
    (df['Score'] >=60) & (df['Attendance']>=70),
    df['Score'] < 60

]
values5 = ["Promoted","Not Promoted"]
df['Status'] = np.select(conditions5,values5,default='other')
df
# -------------------------------------
# After completing all columns, print the final DataFrame

Original DataFrame:
  Student  Score  Attendance
0     Amy     95          98
1   Brian     83          89
2   Clara     76          75
3     Dan     68          70
4    Ella     59          65

,Student,Score,Attendance,Grade,Discipline,Final_Remark,Award,Status
0,Amy,95,98,A,Excellent,Outstanding,Gold,Promoted
1,Brian,83,89,B,Good,Very Good,Bronze,Promoted
2,Clara,76,75,C,Average,Needs Improvement,other,Promoted
3,Dan,68,70,D,Average,Needs Improvement,None,Promoted
4,Ella,59,65,F,Poor,Needs Improvement,None,Not Promoted